name: ADO_test/snsinahub-org.ado-pipeline-migration
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
env:
  tag: "${{ github.run_id }}"
jobs:
  Build-Build:
    name: Build
    runs-on:
      - self-hosted
      - Default
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Build an image
      run: docker build ${{ github.workspace }} --file "${{ github.workspace }}/Dockerfile"
  Build-print_default_working_directory:
    name: print_dir_path
    runs-on:
      - self-hosted
      - Default
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: pwd ${{ github.workspace }}
  Deploy_sandbox-Deploy_sandbox:
    name: Print job name
    needs:
    - Build-Build
    - Build-print_default_working_directory
    runs-on:
      - self-hosted
      - Default
    environment: sandbox
    env:
      url: sandbox.google.com
    if: github.RUN_NUMBER == 1
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: download artifact
      uses: actions/download-artifact@v2
    - name: converted curl command
      uses: wei/curl@master
      with:
        args: "${{ env.url }}"
  Deploy_prod-Deploy:
    name: Print job name
    needs:
    - Deploy_sandbox-Deploy_sandbox
    runs-on:
      - self-hosted
      - Default
    environment: prod
    env:
      url: www.google.com
    if: github.RUN_NUMBER == 1
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: download artifact
      uses: actions/download-artifact@v2
    - name: converted curl command
      uses: wei/curl@master
      with:
        args: "${{ env.url }}"
